# docker-compose
version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3005:3005"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    ports: 
      - "8080:8080"