name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug directory tree
        run: |
          echo "PWD: $(pwd)"
          find . -name go.sum

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Tidy modules
        run: go mod tidy
        
      - name: Placeholder build step
        run: echo "No real build yet, but go mod tidy succeeded!"
        working-directory: backend
